/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardgame.graphics;

import java.awt.Font;

/**
 *
 * @author manos
 */
public class ModeAsker extends javax.swing.JFrame {
    
    int choice;
    /**
     * Creates new form ModeAsker
     */
    public ModeAsker() {
        choice=0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        normalMode = new javax.swing.JRadioButton();
        doubleCards = new javax.swing.JRadioButton();
        SwapMode = new javax.swing.JRadioButton();
        TrioMode = new javax.swing.JRadioButton();
        button = new javax.swing.JButton();
        DontChooseMode = new javax.swing.JRadioButton();
        MonomaxiaMode = new javax.swing.JRadioButton();
        TrioDontChooseMode = new javax.swing.JRadioButton();
        SinglePlayerMode = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ξ ΞΏΞΉΞ± ΞµΞΊΞ΄ΞΏΟ‡Ξ· ΞΈΞµΞ»ΞµΞΉΟ‚ Ξ½Ξ± Ο€Ξ±ΞΉΞΎΞµΞΉΟ‚ ? :");
        jLabel1.setFont(new Font("Ξ ΞΏΞΉΞ± ΞµΞΊΞ΄ΞΏΟ‡Ξ· ΞΈΞµΞ»ΞµΞΉΟ‚ Ξ½Ξ± Ο€Ξ±ΞΉΞΎΞµΞΉΟ‚? :",Font.BOLD,12));

        buttonGroup1.add(normalMode);
        normalMode.setText("Normal mode");
        normalMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalModeActionPerformed(evt);
            }
        });

        buttonGroup1.add(doubleCards);
        doubleCards.setText("Double Cards");

        buttonGroup1.add(SwapMode);
        SwapMode.setText("Swap mode");

        buttonGroup1.add(TrioMode);
        TrioMode.setText("Trio mode");

        button.setText("OK");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(DontChooseMode);
        DontChooseMode.setText("Dont Choose mode");

        buttonGroup1.add(MonomaxiaMode);
        MonomaxiaMode.setText("Monomaxia mode");

        buttonGroup1.add(TrioDontChooseMode);
        TrioDontChooseMode.setText("Trio + Dont Choose");

        buttonGroup1.add(SinglePlayerMode);
        SinglePlayerMode.setText("Single Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrioMode)
                    .addComponent(SwapMode)
                    .addComponent(doubleCards)
                    .addComponent(normalMode)
                    .addComponent(DontChooseMode)
                    .addComponent(MonomaxiaMode)
                    .addComponent(TrioDontChooseMode)
                    .addComponent(SinglePlayerMode))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(SinglePlayerMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normalMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doubleCards)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SwapMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrioMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DontChooseMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TrioDontChooseMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MonomaxiaMode)
                .addGap(29, 29, 29)
                .addComponent(button)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void normalModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalModeActionPerformed

    public int buttonChosen(){
        return choice;
    }
    
    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        if (normalMode.isSelected()==true){
            choice=1;
        }
        else if (doubleCards.isSelected()==true){
            choice=2;
        }
        else if (SwapMode.isSelected()==true){
            choice=3;
        }
        else if (TrioMode.isSelected()==true){
            choice=4;
        }
        else if (DontChooseMode.isSelected()==true){
            choice=5;
        }
        else if (MonomaxiaMode.isSelected()==true){
            choice=6;
        }
        else if (TrioDontChooseMode.isSelected()==true){
            choice=7;
        }
        else{
            choice=8;
        }
        
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DontChooseMode;
    private javax.swing.JRadioButton MonomaxiaMode;
    private javax.swing.JRadioButton SinglePlayerMode;
    private javax.swing.JRadioButton SwapMode;
    private javax.swing.JRadioButton TrioDontChooseMode;
    private javax.swing.JRadioButton TrioMode;
    private javax.swing.JButton button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton doubleCards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton normalMode;
    // End of variables declaration//GEN-END:variables
}

